### ISSUE TITLE
NG 0.8 FC on Moto X 5.1

### ISSUE THREAD

**Issue by agoston** [M66B/NetGuard#15]
Logcat:

```
/SupportMenuInflater( 7976): Cannot instantiate class: android.support.v7.widget.SearchView
W/SupportMenuInflater( 7976): java.lang.NoSuchMethodException: <init> [class android.content.Context]
W/SupportMenuInflater( 7976): 	at java.lang.Class.getConstructor(Class.java:531)
W/SupportMenuInflater( 7976): 	at java.lang.Class.getConstructor(Class.java:495)
W/SupportMenuInflater( 7976): 	at android.support.v7.internal.view.h.a(SourceFile:498)
W/SupportMenuInflater( 7976): 	at android.support.v7.internal.view.h.a(SourceFile:458)
W/SupportMenuInflater( 7976): 	at android.support.v7.internal.view.h.b(SourceFile:479)
W/SupportMenuInflater( 7976): 	at android.support.v7.internal.view.f.a(SourceFile:196)
W/SupportMenuInflater( 7976): 	at android.support.v7.internal.view.f.inflate(SourceFile:118)
W/SupportMenuInflater( 7976): 	at eu.faircode.netguard.ActivityMain.onCreateOptionsMenu(SourceFile:189)
W/SupportMenuInflater( 7976): 	at android.app.Activity.onCreatePanelMenu(Activity.java:2833)
W/SupportMenuInflater( 7976): 	at android.support.v4.b.o.onCreatePanelMenu(SourceFile:298)
W/SupportMenuInflater( 7976): 	at android.support.v7.internal.view.k.onCreatePanelMenu(SourceFile:85)
W/SupportMenuInflater( 7976): 	at android.support.v7.a.u.onCreatePanelMenu(SourceFile:243)
W/SupportMenuInflater( 7976): 	at android.support.v7.a.A.b(SourceFile:1261)
W/SupportMenuInflater( 7976): 	at android.support.v7.a.A.a(SourceFile:14541)
W/SupportMenuInflater( 7976): 	at android.support.v7.a.B.run(SourceFile:130)
W/SupportMenuInflater( 7976): 	at android.os.Handler.handleCallback(Handler.java:739)
W/SupportMenuInflater( 7976): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/SupportMenuInflater( 7976): 	at android.os.Looper.loop(Looper.java:135)
W/SupportMenuInflater( 7976): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
W/SupportMenuInflater( 7976): 	at java.lang.reflect.Method.invoke(Native Method)
W/SupportMenuInflater( 7976): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/SupportMenuInflater( 7976): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
W/SupportMenuInflater( 7976): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
D/AndroidRuntime( 7976): Shutting down VM
E/AndroidRuntime( 7976): FATAL EXCEPTION: main
E/AndroidRuntime( 7976): Process: eu.faircode.netguard, PID: 7976
E/AndroidRuntime( 7976): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.a(android.support.v7.widget.bf)' on a null object reference
E/AndroidRuntime( 7976): 	at eu.faircode.netguard.ActivityMain.onCreateOptionsMenu(SourceFile:194)
E/AndroidRuntime( 7976): 	at android.app.Activity.onCreatePanelMenu(Activity.java:2833)
E/AndroidRuntime( 7976): 	at android.support.v4.b.o.onCreatePanelMenu(SourceFile:298)
E/AndroidRuntime( 7976): 	at android.support.v7.internal.view.k.onCreatePanelMenu(SourceFile:85)
E/AndroidRuntime( 7976): 	at android.support.v7.a.u.onCreatePanelMenu(SourceFile:243)
E/AndroidRuntime( 7976): 	at android.support.v7.a.A.b(SourceFile:1261)
E/AndroidRuntime( 7976): 	at android.support.v7.a.A.a(SourceFile:14541)
E/AndroidRuntime( 7976): 	at android.support.v7.a.B.run(SourceFile:130)
E/AndroidRuntime( 7976): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 7976): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 7976): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 7976): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime( 7976): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7976): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 7976): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime( 7976): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
W/ActivityManager(  911):   Force finishing activity 1 eu.faircode.netguard/.ActivityMain
```

**Comment by M66B** [comment]
Which version of NetGuard? The proguard variant?

**Comment by M66B** [comment]
Looking at the log, I guess you were using the proguard variant.

Could you please try NetGuard-v0.8-proguard-2.apk from here:
https://github.com/M66B/NetGuard/releases/tag/0.8

and let me know if the problem is fixed?

**Comment by agoston** [comment]
Yup, the non-proguard variant works!

**Comment by M66B** [comment]
Could you please try if **NetGuard-v0.8-proguard-2.apk** fixes the problem:
https://github.com/M66B/NetGuard/releases/tag/0.8

**Comment by agoston** [comment]
Yup! Now it works great.
Thanks!

**Comment by M66B** [comment]
Thanks for reporting back!
