### ISSUE TITLE
Crash if no internet connection

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#250]
no-root Samsung 5.0.2, NetGuard 0.77-beta3

In logcat at 16:22:10 I guess: https://gist.github.com/licaon-kter/2d6ace3513a3af250132 (there's the tether issue there too, you'll recognize it easily by 225.0.0.0)

One thing of note here, on Xperia 5.1.1 it does not happen BUT I don't need filter activated there to work anyway, so it might be the same as: https://github.com/M66B/NetGuard/issues/247

**Comment by M66B** [comment]
Trivial mistake ...

**Comment by M66B** [comment]
Keep on testing!

**Comment by licaon-kter** [comment]
10q

**Comment by licaon-kter** [comment]
Xperia 5.1.1
0.77-beta5

```
NetGuard.Service: DNS system=my.dns.ip.yeah VPN=
01-26 00:40:29.513 23739 23815 E NetGuard.Service: java.lang.IllegalArgumentException: Bad address
01-26 00:40:29.513 23739 23815 E NetGuard.Service: java.lang.IllegalArgumentException: Bad address
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at android.net.VpnService$Builder.addDnsServer(VpnService.java:536)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at android.net.VpnService$Builder.addDnsServer(VpnService.java:557)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService.startVPN(SourceFile:673)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService.access$1300(SourceFile:76)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$ServiceHandler.start(SourceFile:324)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$ServiceHandler.handleIntent(SourceFile:259)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$ServiceHandler.handleMessage(SourceFile:168)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at android.os.Looper.loop(Looper.java:211)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at android.os.HandlerThread.run(HandlerThread.java:61)
01-26 00:40:29.514 23739 23739 I NetGuard.Main: Preference enabled=false
```
