### ISSUE TITLE
Error when upgrading from DB version 5 to 9

### ISSUE THREAD

**Issue by marco-scavuzzo** [M66B/NetGuard#256]
```
01-28 09:55:16.220  14135-14135/? I/NetGuard.Database﹕ Netguard upgrading from version 5 to 9
01-28 09:55:16.225  14135-14135/? I/NetGuard.Database﹕ Creating log table
01-28 09:55:16.242  14135-14135/? E/NetGuard.Database﹕ android.database.sqlite.SQLiteException: duplicate column name: data (code 1): , while compiling: ALTER TABLE log ADD COLUMN data TEXT
    android.database.sqlite.SQLiteException: duplicate column name: data (code 1): , while compiling: ALTER TABLE log ADD COLUMN data TEXT
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
            at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
            at eu.faircode.netguard.DatabaseHelper.onUpgrade(SourceFile:132)
            at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
            at eu.faircode.netguard.DatabaseHelper.getLog(SourceFile:232)
            at eu.faircode.netguard.ActivityLog.onCreate(SourceFile:103)
            at android.app.Activity.performCreate(Activity.java:6251)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
            at android.app.ActivityThread.-wrap11(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by M66B** [comment]
That's not nice.

Workaround:
* Export settings
* Clear data using Android settings
* Import settings
* Enable NetGuard again

I will look into it.

**Comment by malitech** [comment]
This error occurred to me today when I installed v0.82 beta. I was using v0.76.

**Comment by M66B** [comment]
Please provide logcat, so I can see what is going wrong.

**Comment by M66B** [comment]
@malitech: the next version should fix this problem.

**Comment by malitech** [comment]
Thank you. :)
