### ISSUE TITLE
Compact tethering routing table

### ISSUE THREAD

**Issue by Gregy** [M66B/NetGuard#342]
Hi,
I noticed that when tethering is enabled NetGuard creates awful lot of routes (https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/SinkholeService.java#L919)

What about using this code instead?
```
     builder.addRoute("0.0.0.0", 1); //0-127 - includes localhost but it shouldn't matter
     builder.addRoute("128.0.0.0", 2); //128-191
     builder.addRoute("192.0.0.0", 9); //192.0 - 192.127
     builder.addRoute("192.128.0.0", 11); //192.128 - 192.159
     builder.addRoute("192.160.0.0", 13); //192.160 - 192.167
     builder.addRoute("192.168.0.0", 19); //192.168.0 - 192.168.31
     builder.addRoute("192.168.32.0", 21); //192.168.32 - 192.168.39
     builder.addRoute("192.168.40.0", 23); //192.168.40 - 192.168.41
     //skip 192.168.42 - 192.168.43
     builder.addRoute("192.168.44.0", 22); //192.168.44 - 192.168.47
     builder.addRoute("192.168.48.0", 20); //192.168.48 - 192.168.63
     builder.addRoute("192.168.64.0", 18); //192.168.64 - 192.168.127
     builder.addRoute("192.168.128.0", 17); //192.168.128 - 192.168.255
     builder.addRoute("192.169.0.0", 16); //192.169 
     builder.addRoute("192.170.0.0", 15); //192.170 - 192.171
     builder.addRoute("192.172.0.0", 14); //192.172 - 192.175
     builder.addRoute("192.176.0.0", 12); //192.176 - 192.191
     builder.addRoute("192.192.0.0", 10); //192.192 - 192.255
     builder.addRoute("193.0.0.0", 8); //193
     builder.addRoute("194.0.0.0", 7); //194 - 195
     builder.addRoute("196.0.0.0", 6); //196 - 199
     builder.addRoute("200.0.0.0", 5); //200 - 207
     builder.addRoute("208.0.0.0", 4); //208 - 223
```

It should theoretically take less time for table building and packet lookup.

What do you think?

Unfortunately it is not tested. I do not yet have android building capability :(

**Comment by M66B** [comment]
Yes, that would be an improvement, but including localhost will fail on some devices.

**Comment by Gregy** [comment]
Ah, ok. I will rework the table to exclude it.

**Comment by M66B** [comment]
The idea is good though, if you rework the table and make sure the end result is the same as the current solution I will implement and test it.

**Comment by M66B** [comment]
And yes, my solution was quick and dirty, because my to do list was quite long at the time I wrote this.
Also the priority was to get the TCP/IP stack stable, which seems okay now (there were a lot of details in the stack that needed attention).

**Comment by Gregy** [comment]
Yes, I understand that. I think optimizations are usually done only after everything works fine because it is usually harder to edit optimized code. 

I started thinking about this because the strange leak/tethering correlation from #341. I don't think this will help but I just noticed something I could (hopefully) help improve.

Here is reworked table:
```
builder.addRoute("0.0.0.0", 2); //0-63 
builder.addRoute("64.0.0.0", 3); //64-95
builder.addRoute("96.0.0.0", 4); //96-111
builder.addRoute("112.0.0.0", 5); //112-120
builder.addRoute("120.0.0.0", 6); //120-123
builder.addRoute("124.0.0.0", 7); //124-125
builder.addRoute("126.0.0.0", 8); //126
// skip 127.0.0.0/8 - localhost
builder.addRoute("128.0.0.0", 2); //128-191
builder.addRoute("192.0.0.0", 9); //192.0 - 192.127
builder.addRoute("192.128.0.0", 11); //192.128 - 192.159
builder.addRoute("192.160.0.0", 13); //192.160 - 192.167
builder.addRoute("192.168.0.0", 19); //192.168.0 - 192.168.31
builder.addRoute("192.168.32.0", 21); //192.168.32 - 192.168.39
builder.addRoute("192.168.40.0", 23); //192.168.40 - 192.168.41
// skip 192.168.42 - 192.168.43
builder.addRoute("192.168.44.0", 22); //192.168.44 - 192.168.47
builder.addRoute("192.168.48.0", 20); //192.168.48 - 192.168.63
builder.addRoute("192.168.64.0", 18); //192.168.64 - 192.168.127
builder.addRoute("192.168.128.0", 17); //192.168.128 - 192.168.255
builder.addRoute("192.169.0.0", 16); //192.169  
builder.addRoute("192.170.0.0", 15); //192.170 - 192.171
builder.addRoute("192.172.0.0", 14); //192.172 - 192.175
builder.addRoute("192.176.0.0", 12); //192.176 - 192.191
builder.addRoute("192.192.0.0", 10); //192.192 - 192.255
builder.addRoute("193.0.0.0", 8); //193
builder.addRoute("194.0.0.0", 7); //194 - 195
builder.addRoute("196.0.0.0", 6); //196 - 199
builder.addRoute("200.0.0.0", 5); //200 - 207
builder.addRoute("208.0.0.0", 4); //208 - 223
```
It should have exactly same effect as current code. Just with less routing entries.

**Comment by M66B** [comment]
The target is to route 1-223 into the VPN (which makes me wonder if broadcast addresses shouldn't be routed into the VPN as well, despite some Android versions having trouble with this), but excluding the 127, 192.168.42 and 192.168.43 net.

Let me check without looking at your range remarks so we don't make a trivial mistake we regret later:
```
builder.addRoute("0.0.0.0", 2); // 0-63
builder.addRoute("64.0.0.0", 3); // 64-95
builder.addRoute("96.0.0.0", 4); // 96-111
builder.addRoute("112.0.0.0", 5); // 112-119
builder.addRoute("120.0.0.0", 6); // 120-123
builder.addRoute("124.0.0.0", 7); // 124-125
builder.addRoute("126.0.0.0", 8); // 126
// skip 127.0.0.0/8 - localhost
builder.addRoute("128.0.0.0", 2); // 128-191
builder.addRoute("192.0.0.0", 9); // 192.0-192.127
builder.addRoute("192.128.0.0", 11); // 192.128-192.159
builder.addRoute("192.160.0.0", 13); // 192.160-192.167
builder.addRoute("192.168.0.0", 19); // 192.168.0-192.168.31
builder.addRoute("192.168.32.0", 21); // 192.168.32-192.168.39
builder.addRoute("192.168.40.0", 23); // 192.168.40-192.168.41
// skip 192.168.42 - 192.168.43
builder.addRoute("192.168.44.0", 22); // 192.168.44-192.168.47
builder.addRoute("192.168.48.0", 20); // 192.168.48-192.168.63
builder.addRoute("192.168.64.0", 18); // 192.168.64-192.168.127
builder.addRoute("192.168.128.0", 17); // 192.168.128-192.168.255
builder.addRoute("192.169.0.0", 16); // 192.169
builder.addRoute("192.170.0.0", 15); // 192.170-192.171
builder.addRoute("192.172.0.0", 14); // 192.172-192.175
builder.addRoute("192.176.0.0", 12); // 192.176-191.191
builder.addRoute("192.192.0.0", 10); // 192.192-192.255
builder.addRoute("193.0.0.0", 8); // 193
builder.addRoute("194.0.0.0", 7); // 194-195
builder.addRoute("196.0.0.0", 6); // 196-199
builder.addRoute("200.0.0.0", 5); // 200-207
builder.addRoute("208.0.0.0", 4); // 208-223
```
Comparing it, you have a little error in a remark, but the result is the same, so we are good to go.

**Comment by M66B** [comment]
The Android connectivity services agrees on my Nexus 5 / Marshmallow:
```
02-21 19:28:49.389   783   889 D ConnectivityService: Adding Route [0.0.0.0/2 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.389   783   889 D ConnectivityService: Adding Route [64.0.0.0/3 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.390   783   889 D ConnectivityService: Adding Route [96.0.0.0/4 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.390   783   889 D ConnectivityService: Adding Route [112.0.0.0/5 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.391   783   889 D ConnectivityService: Adding Route [120.0.0.0/6 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.392   783   889 D ConnectivityService: Adding Route [124.0.0.0/7 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.392   783   889 D ConnectivityService: Adding Route [126.0.0.0/8 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.393   783   889 D ConnectivityService: Adding Route [128.0.0.0/2 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.393   783   889 D ConnectivityService: Adding Route [192.0.0.0/9 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.394   783   889 D ConnectivityService: Adding Route [192.128.0.0/11 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.394   783   889 D ConnectivityService: Adding Route [192.160.0.0/13 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.397   783   889 D ConnectivityService: Adding Route [192.168.0.0/19 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.398   783   889 D ConnectivityService: Adding Route [192.168.32.0/21 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.399   783   889 D ConnectivityService: Adding Route [192.168.40.0/23 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.400   783   889 D ConnectivityService: Adding Route [192.168.44.0/22 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.400   783   889 D ConnectivityService: Adding Route [192.168.48.0/20 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.401   783   889 D ConnectivityService: Adding Route [192.168.64.0/18 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.402   783   889 D ConnectivityService: Adding Route [192.168.128.0/17 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.403   783   889 D ConnectivityService: Adding Route [192.169.0.0/16 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.405   783   889 D ConnectivityService: Adding Route [192.170.0.0/15 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.406   783   889 D ConnectivityService: Adding Route [192.172.0.0/14 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.407   783   889 D ConnectivityService: Adding Route [192.176.0.0/12 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.409   783   889 D ConnectivityService: Adding Route [192.192.0.0/10 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.410   783   889 D ConnectivityService: Adding Route [193.0.0.0/8 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.410   783   889 D ConnectivityService: Adding Route [194.0.0.0/7 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.411   783   889 D ConnectivityService: Adding Route [196.0.0.0/6 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.411   783   889 D ConnectivityService: Adding Route [200.0.0.0/5 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.412   783   889 D ConnectivityService: Adding Route [208.0.0.0/4 -> 0.0.0.0 tun1] to network 293
02-21 19:28:49.413   783   889 D ConnectivityService: Adding Route [::/0 -> :: tun1] to network 293
```

**Comment by Gregy** [comment]
Great. Thanks :)

**Comment by M66B** [comment]
Can you check this addition, for broadcast routing:

224.0.0.0/4
240.0.0.0/4
255.255.255.255/32

**Comment by M66B** [comment]
Test version:
https://github.com/M66B/NetGuard/releases/tag/0.91

**Comment by Gregy** [comment]
As far as the routes go it appears fine but there is strange MTU error just before the first route. I thought NetGuard sets the MTU very high to avoid fragmentation.
```
E/ConnectivityService( 1430): Unexpected mtu value: 0, tun0
D/ConnectivityService( 1430): Adding Route [0.0.0.0/2 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [64.0.0.0/3 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [96.0.0.0/4 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [112.0.0.0/5 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [120.0.0.0/6 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [124.0.0.0/7 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [126.0.0.0/8 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [128.0.0.0/2 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.0.0.0/9 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.128.0.0/11 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.160.0.0/13 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.168.0.0/19 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.168.32.0/21 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.168.40.0/23 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.168.44.0/22 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.168.48.0/20 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.168.64.0/18 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.168.128.0/17 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.169.0.0/16 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.170.0.0/15 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.172.0.0/14 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [192.176.0.0/12 -> 0.0.0.0 tun0] to network 106
E/NativeDaemonConnector.ResponseQueue( 1430): more buffered than allowed: 10 >= 10
E/NativeDaemonConnector.ResponseQueue( 1430): Removing request: null (2537)
D/ConnectivityService( 1430): Adding Route [192.192.0.0/10 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [193.0.0.0/8 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [194.0.0.0/7 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [196.0.0.0/6 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [200.0.0.0/5 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [208.0.0.0/4 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [224.0.0.0/4 -> 0.0.0.0 tun0] to network 106
W/NetGuard.JNI(14980): Starting tun 88 fwd53 0 level 5 thread 0
W/NetGuard.JNI(14980): Started thread e0d22000
W/NetGuard.JNI(14980): Start events tun=88 thread e0d22000
D/ConnectivityService( 1430): Adding Route [240.0.0.0/4 -> 0.0.0.0 tun0] to network 106
D/ConnectivityService( 1430): Adding Route [::/0 -> :: tun0] to network 106
D/ConnectivityService( 1430): Setting Dns servers for network 106 to [/fd6a:be99:5dbb::1, /192.168.18.1]
```
Android: 5.1.1 (SDK 22) on Sony Z5 compact

**Comment by M66B** [comment]
I have that message too, but the MTU is set as intended:

```
shell@hammerhead:/ $ ifconfig
...
tun0      Link encap:UNSPEC  
          inet addr:10.1.10.1  P-t-P:10.1.10.1  Mask:255.255.255.255 
          inet6 addr: fd00:1:fd00:1:fd00:1:fd00:1/64 Scope: Global
          UP POINTOPOINT RUNNING  MTU:32768  Metric:1
          RX packets:398 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:380 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:500 
          RX bytes:126548 TX bytes:40661 
...
```

**Comment by M66B** [comment]
I am glad somebody is understanding what I am trying to do with the MTU and the routing table :-)

**Comment by M66B** [comment]
If you have any other remarks, please let me know.

**Comment by M66B** [comment]
The MTU message is coming from here:
https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/ConnectivityService.java#1653

**Comment by M66B** [comment]
Reducing the MTU value to the maximum of 10000 doesn't remove the message
```
02-21 20:16:20.696   783   889 D ConnectivityService: Adding iface tun0 to network 297
02-21 20:16:20.730   783   889 E ConnectivityService: Unexpected mtu value: 0, tun0
```

**Comment by licaon-kter** [comment]
Samsung, 5.0.2, (not tethering before), now plain crashing on tether activate: 
```
02-21 21:15:36.280  9096  9238 E NetGuard.Service: java.lang.IllegalArgumentException: Bad LinkAddress params /224.0.0.0/4
02-21 21:15:36.280  9096  9238 E NetGuard.Service: java.lang.IllegalArgumentException: Bad LinkAddress params /224.0.0.0/4
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at android.net.LinkAddress.init(LinkAddress.java:104)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at android.net.LinkAddress.<init>(LinkAddress.java:124)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at android.net.LinkAddress.<init>(LinkAddress.java:135)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at android.net.VpnService$Builder.addRoute(VpnService.java:519)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at android.net.VpnService$Builder.addRoute(VpnService.java:536)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at eu.faircode.netguard.SinkholeService$Builder.addRoute(SourceFile:2010)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at eu.faircode.netguard.SinkholeService.getBuilder(SourceFile:951)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at eu.faircode.netguard.SinkholeService.access$1900(SourceFile:90)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at eu.faircode.netguard.SinkholeService$CommandHandler.start(SourceFile:370)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at eu.faircode.netguard.SinkholeService$CommandHandler.handleIntent(SourceFile:299)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at eu.faircode.netguard.SinkholeService$CommandHandler.handleMessage(SourceFile:215)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at android.os.Handler.dispatchMessage(Handler.java:102)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at android.os.Looper.loop(Looper.java:145)
02-21 21:15:36.280  9096  9238 E NetGuard.Service:      at android.os.HandlerThread.run(HandlerThread.java:61)
```

You fixed it before: https://github.com/M66B/NetGuard/issues/42#issuecomment-174297011

**Comment by M66B** [comment]
This is a bug in Android, because it should be possible to route broadcast addresses into the VPN.
I will workaround it.

**Comment by M66B** [comment]
@licaon-kter test version:
http://www.netguard.me/NetGuard-v0.91-beta-2016022104-all-release-broadcast.apk

**Comment by Gregy** [comment]
Just reporting that with the above version I still have the MTU error message but the interface is correctly setup with MTU 10000. Everything seems to work fine.

**Comment by licaon-kter** [comment]
Ok that fixed the crash, still no tether working (no surprise there though).

**Comment by Gregy** [comment]
@licaon-kter Do you know why it doesn't work? If not could you enable tethering and netguard and post results of these commands?
```
ip a s
ip rule show
ip route show table all
```

**Comment by licaon-kter** [comment]
[ip a s](https://gist.github.com/licaon-kter/a43f5d296d0a49f04a76)
[ip rule show](https://gist.github.com/licaon-kter/db3206c80d4f3e68bd9e)
[ip route show table all](https://gist.github.com/licaon-kter/617a1f34fd7a82a6b4ad)

**Comment by M66B** [comment]
Assuming you have tethering in NetGuard enabled and the NetGuard VPN running, your Android version is not executing the addRoute API, because these lines are missing in the route table:

```
0.0.0.0/2 dev tun0  table 1222  proto static  scope link 
64.0.0.0/3 dev tun0  table 1222  proto static  scope link 
96.0.0.0/4 dev tun0  table 1222  proto static  scope link 
112.0.0.0/5 dev tun0  table 1222  proto static  scope link 
120.0.0.0/6 dev tun0  table 1222  proto static  scope link 
124.0.0.0/7 dev tun0  table 1222  proto static  scope link 
126.0.0.0/8 dev tun0  table 1222  proto static  scope link 
128.0.0.0/2 dev tun0  table 1222  proto static  scope link 
192.0.0.0/9 dev tun0  table 1222  proto static  scope link 
192.128.0.0/11 dev tun0  table 1222  proto static  scope link 
192.160.0.0/13 dev tun0  table 1222  proto static  scope link 
192.168.0.0/19 dev tun0  table 1222  proto static  scope link 
192.168.32.0/21 dev tun0  table 1222  proto static  scope link 
192.168.40.0/23 dev tun0  table 1222  proto static  scope link 
192.168.44.0/22 dev tun0  table 1222  proto static  scope link 
192.168.48.0/20 dev tun0  table 1222  proto static  scope link 
192.168.64.0/18 dev tun0  table 1222  proto static  scope link 
192.168.128.0/17 dev tun0  table 1222  proto static  scope link 
192.169.0.0/16 dev tun0  table 1222  proto static  scope link 
192.170.0.0/15 dev tun0  table 1222  proto static  scope link 
192.172.0.0/14 dev tun0  table 1222  proto static  scope link 
192.176.0.0/12 dev tun0  table 1222  proto static  scope link 
192.192.0.0/10 dev tun0  table 1222  proto static  scope link 
193.0.0.0/8 dev tun0  table 1222  proto static  scope link 
194.0.0.0/7 dev tun0  table 1222  proto static  scope link 
196.0.0.0/6 dev tun0  table 1222  proto static  scope link 
200.0.0.0/5 dev tun0  table 1222  proto static  scope link 
208.0.0.0/4 dev tun0  table 1222  proto static  scope link 
224.0.0.0/4 dev tun0  table 1222  proto static  scope link 
240.0.0.0/4 dev tun0  table 1222  proto static  scope link 
```

In English: due to a deficiency in your ROM the NetGuard tether workaround doesn't work for you, but you already known that.

**Comment by Gregy** [comment]
The strange thing is this rule:
```
default dev tun0  table 1545  proto static  metric 1024
```

Where does it come from? This would be expected if the tethering is off but if it is on there should be no default ipv4 route added. Only some smaller routes. 

@licaon-kter Can you get adb logcat (via usb debugging because I think the one integrated in netguard doesn't cover system messages)? It should start with netguard disabled and should cover starting netguard filtering with tethering on.

**Comment by licaon-kter** [comment]
`adb logcat -v threadtime > logcat.txt`
then
`grep -i -e "ConnectivityService" -e "NetGuard" -e "vpn" -e "tether" -e "hotspot" logcat.txt >logcat_grep.txt `

Enjoy: https://gist.github.com/licaon-kter/10e4343dca0ed47464a2
Do tell me if you want some other buzzword added to the *grep*.

**Comment by licaon-kter** [comment]
Some notices:
* `ConnectivityService: establishVpn called by non-knox vpn`
* `VpnJni  :  knox vpn meta not enabled`

Meaning this [KNOX VPN SDK](https://seap.samsung.com/knoxportal/files/html-doc/unzip/1627/en/VPN-Service-SDK-Dev-Guide/Default.htm#KNOX VPN Services SDK Developer Guide/Integrating apps with KNOX.htm%3FTocPath%3DIntegrating%2520apps%2520with%2520KNOX%2520VPN%2520network%2520framework%7C_____0) I guess. 

And:
* `Tethering: interfaceAdded tun0
* `Tethering: tun0 is not a tetherable iface, ignoring`

**Comment by licaon-kter** [comment]
Some issues mentioning Samsung: [Issue 64819: post 38 might have a fix](https://code.google.com/p/android/issues/detail?id=64819#c38) and another one with MSS ([not sure if fixed in >5](http://developer.samsung.com/forum/board/thread/view.do?boardName=General&messageId=259244))

Another clue, since I have `10.xxx.xxx.128/29 dev rmnet0` [above](https://github.com/M66B/NetGuard/issues/342#issuecomment-187044754):
*The app may have issues when a private IP address range within the VPN overlaps with the range of the outside interface of the client device. When this route overlap occurs, the user may be able to successfully connect to the VPN but then be unable to actually access anything. This issue has been seen on cellular networks which use NAT (Network Address Translation) and assign addresses within the 10.0.0.0 - 10.255.255.255 range, and is due to the app having limited control of routes in the Android VPN framework. The vendor specific Android packages have full routing control and may work better in such a scenario.*

**Comment by M66B** [comment]
Try changing the VPN address to 192.168.168.168 for example (in stead of the default 10.1.10.1)

**Comment by licaon-kter** [comment]
No joy, at least the Wi-Fi icon is sometimes full (filled with white), if not with an exclamation mark or just empty (not as `empty since not connected` but emply as filled with gray).
Also at least 3 ICMPs passed once in a blue moon (164/165/166'th and on another time 204/205/206'th adnd then 316/317/318; always pack of 3), so it's... closer.

**Comment by M66B** [comment]
@Gregy to what local address should the sockets be bound to forward the traffic? To the local VPN address or the local interface address?

The sockets are currently bound to any address (no explicit bounding is done). The sockets live outside the VPN, so binding to the local interface address should be logical. Binding to one interface address could result in issue when connectivity changes though, so I rather leave it like it is.

**Comment by Gregy** [comment]
Precisely. If at all it should be bound to local address of the wifi/rmnet interface. However if bound the socket would have to be recreated on each connectivity change. I wouldn't do it. It would bring more problems and probably solve none (certainly not this one).

The problem seems to be like @M66B said earlier that Android Framework eats up the routing config and replaces it with wildcard route. That would explain both the broken tethering and broken netguard without filtering enabled. I would go so far as to point the finger at Samsung KNOX framework which seems to be precisely the thing that mucks with Android VPN internals. @licaon-kter if you cannot uninstall KNOX then I think you are screwed, sorry :(

**Comment by licaon-kter** [comment]
That's like glued here, I'll see too it, although if it's not already disabled then it could not be done.
