### ISSUE TITLE
Failing to start in 2.0/2.1 on Samsung 5.0.2

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#357]
```
NetGuard.Service: Start intent=Intent { cmp=eu.faircode.netguard/.SinkholeService (has extras) } command=reload reason=pull vpn=false user=0
NetGuard.Service: Executing intent=Intent { cmp=eu.faircode.netguard/.SinkholeService (has extras) } command=reload reason=pull vpn=false user=0
NetGuard.Main: Received Intent { act=eu.faircode.netguard.ACTION_QUEUE_CHANGED (has extras) }
NetGuard.Util: Size=1 (Integer)
NetGuard.Service: Get allowed connected=false wifi=false home= network=<unknown ssid> metered=false/false generation=null roaming=false/false interactive=true tethering=false filter=true
NetGuard.Service: Allowed 0 of 323
NetGuard.Service: vpn4=10.1.10.1 vpn6=fd00:1:fd00:1:fd00:1:fd00:1
NetGuard.Service: DNS system=208.67.220.220 VPN=null
NetGuard.Service: dns=/208.67.220.220
NetGuard.Service: Legacy restart
NetGuard.Service: java.lang.IllegalStateException: VPN start failed
NetGuard.Service: java.lang.IllegalStateException: VPN start failed
NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$CommandHandler.reload(SourceFile:463)
NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$CommandHandler.handleIntent(SourceFile:314)
NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$CommandHandler.handleMessage(SourceFile:226)
NetGuard.Service: 	at android.os.Handler.dispatchMessage(Handler.java:102)
NetGuard.Service: 	at android.os.Looper.loop(Looper.java:145)
NetGuard.Service: 	at android.os.HandlerThread.run(HandlerThread.java:61)
NetGuard.Service: Messages=false wakelock=false
NetGuard.Main: Received Intent { act=eu.faircode.netguard.ACTION_QUEUE_CHANGED (has extras) }
NetGuard.Util: Size=0 (Integer)
```

**Comment by M66B** [comment]
I cannot fix this, because it is caused by a bug in Android.
It is already the legacy full restart, so there is little else I can do.

**Comment by licaon-kter** [comment]
It worked up to 0.98 so it's something new.

**Comment by M66B** [comment]
The code was not changed (just a little bit refactored, but it does the same).

My best guess is that you need to approve the VPN again (while Android reports to NetGuard it is already approved).

**Comment by licaon-kter** [comment]
This https://github.com/M66B/NetGuard/commit/4e7eb2674c741931ea1a8541f5749ad3f20fcb65 yeah

**Comment by M66B** [comment]
That commit is just refactoring.

By revoking the approval from the Android settings.

**Comment by licaon-kter** [comment]
You know you are in trouble when Google search gives you this answer: https://github.com/M66B/NetGuard/pull/101/files

No idea (yet) on how to revoke :(

**Comment by M66B** [comment]
Uninstall and install again as a last resort.

**Comment by licaon-kter** [comment]
A reboot did it, I un/reinstalled it 2 or 3 times already.

**Comment by M66B** [comment]
I am quite sure this is a bug in Android.

**Comment by licaon-kter** [comment]
Like so many others.
