### ISSUE TITLE
Could not establish VPN

### ISSUE THREAD

**Issue by lequangliem** [M66B/NetGuard#358]
Hello, 

Today, I try to build NetGuard v0.88 beta on LG D805 (LG G2) Android 4.4.2.

The key ( the icon of VPN) on notification is shown, but logcat display : 

```
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               java.lang.IllegalStateException: command 117 interface fwmark uid add tun1 0 99999 failed with 400 117 Failed to add uid rule (Invalid argument) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               java.lang.IllegalStateException: command 117 interface fwmark uid add tun1 0 99999 failed with 400 117 Failed to add uid rule (Invalid argument) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at android.os.Parcel.readException(Parcel.java:1473) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at android.os.Parcel.readException(Parcel.java:1419) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1814) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at android.net.VpnService$Builder.establish(VpnService.java:471) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at eu.faircode.netguard.SinkholeService.startVPN(SinkholeService.java:1018) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at eu.faircode.netguard.SinkholeService.access$1000(SinkholeService.java:65) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at eu.faircode.netguard.SinkholeService$CommandHandler.reload(SinkholeService.java:415) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at eu.faircode.netguard.SinkholeService$CommandHandler.handleIntent(SinkholeService.java:270) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at eu.faircode.netguard.SinkholeService$CommandHandler.handleMessage(SinkholeService.java:181) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at android.os.Handler.dispatchMessage(Handler.java:102) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at android.os.Looper.loop(Looper.java:136) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at android.os.HandlerThread.run(HandlerThread.java:61) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               java.lang.IllegalStateException: Handover failed 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               java.lang.IllegalStateException: Handover failed 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at eu.faircode.netguard.SinkholeService$CommandHandler.reload(SinkholeService.java:417) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at eu.faircode.netguard.SinkholeService$CommandHandler.handleIntent(SinkholeService.java:270) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at eu.faircode.netguard.SinkholeService$CommandHandler.handleMessage(SinkholeService.java:181) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at android.os.Handler.dispatchMessage(Handler.java:102) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at android.os.Looper.loop(Looper.java:136) 
> 03-02 10:07:48.425 E 9655     9672     NetGuard.Service:                               	at android.os.HandlerThread.run(HandlerThread.java:61) 
> 
```

This is not a bug of Android Version or device. I'm sure that because other applications using vpn work OK.

**Comment by M66B** [comment]
This problem is caused by a bug in Android

**Comment by licaon-kter** [comment]
@lequangliem  Any reason not to use latest version (either compile 2.2 or prebuilt)?

**Comment by M66B** [comment]
@lequangliem good question of @licaon-kter , since there has been a workaround for this implemented, which might solve your problem.

**Comment by lequangliem** [comment]
Ok. Thanks for your suggestion. I will try it at the lastest version and notify result later.
