### ISSUE TITLE
Update - version compare error disables NetGuard

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#365]
Build was named `2.5-beta-proxy`, while it would fail to find an update, it should not affect NetGuard otherwise.

```
03-10 08:44:09.542 20485 20519 I NetGuard.Service: Tag 2.5 name NetGuard-v2.5-2016030701-all-release.apk url https://github.com/M66B/NetGuard/releases/download/2.5/NetGuard-v2.5-2016030701-all-release.apk
03-10 08:44:09.543 20485 20519 E NetGuard.Service: java.lang.NumberFormatException: Invalid int: "5-proxy"
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at java.lang.Integer.invalidInt(Integer.java:138)
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at java.lang.Integer.parse(Integer.java:410)
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at java.lang.Integer.parseInt(Integer.java:367)
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at java.lang.Integer.parseInt(Integer.java:334)
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at eu.faircode.netguard.Version.compareTo(Version.java:36)
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$CommandHandler.checkUpdate(SinkholeService.java:582)
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$CommandHandler.householding(SinkholeService.java:546)
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$CommandHandler.handleIntent(SinkholeService.java:344)
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$CommandHandler.handleMessage(SinkholeService.java:239)
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at android.os.Looper.loop(Looper.java:211)
03-10 08:44:09.543 20485 20519 E NetGuard.Service: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

Needs a exception catcher I guess.

**Comment by M66B** [comment]
Version numbers like this are not supported
