### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by gorio** [M66B/NetGuard#417]
I have the latest version of your code

Line before Error
NetGuard.IPUtil: 224.0.0.0/3=224.0.0.0...255.255.255.255

java.lang.IllegalArgumentException: Bad LinkAddress params /224.0.0.0/3
                                                                            java.lang.IllegalArgumentException: Bad LinkAddress params /224.0.0.0/3
                                                                                at android.net.LinkAddress.init(LinkAddress.java:104)
                                                                                at android.net.LinkAddress.<init>(LinkAddress.java:124)
                                                                                at android.net.LinkAddress.<init>(LinkAddress.java:135)
                                                                                at android.net.VpnService$Builder.addRoute(VpnService.java:519)
                                                                                at eu.faircode.netguard.ServiceSinkhole.getBuilder(ServiceSinkhole.java:1041)
                                                                                at eu.faircode.netguard.ServiceSinkhole.access$1900(ServiceSinkhole.java:108)
                                                                                at eu.faircode.netguard.ServiceSinkhole$CommandHandler.reload(ServiceSinkhole.java:419)
                                                                                at eu.faircode.netguard.ServiceSinkhole$CommandHandler.handleIntent(ServiceSinkhole.java:324)
                                                                                at eu.faircode.netguard.ServiceSinkhole$CommandHandler.handleMessage(ServiceSinkhole.java:236)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:145)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by M66B** [comment]
This exception is properly handled by NetGuard and thus not a problem. The cause of s a bug in your Android version.

**Comment by licaon-kter** [comment]
Device? Android version?
