### ISSUE TITLE
FC when enabling NetGuard

### ISSUE THREAD

**Issue by Primokorn** [M66B/NetGuard#6]
I have a FC after switching on the service.
Log: https://db.tt/noAHGnJe

Nexus 5 / Android 5.1.1

**Comment by M66B** [comment]
My best guess is this is caused by a problem in your ROM:

```
10-27 16:39:47.103 E/AndroidRuntime(19545): FATAL EXCEPTION: main
10-27 16:39:47.103 E/AndroidRuntime(19545): Process: com.android.vpndialogs, PID: 19545
10-27 16:39:47.103 E/AndroidRuntime(19545): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog}: java.lang.ClassNotFoundException: Didn't find class "com.android.vpndialogs.ConfirmDialog" on path: DexPathList[[zip file "/system/priv-app/VpnDialogs/VpnDialogs.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
```

I will look into this more detailed later this week.

**Comment by M66B** [comment]
Determined to be caused by a bug in the ROM.

**Comment by M66B** [comment]
```
0-27 16:08:07.338 I/ActivityManager(  840): Start proc 8854:com.android.vpndialogs/u0a19 for activity com.android.vpndialogs/.ConfirmDialog
--------- beginning of crash
10-27 16:08:07.589 E/AndroidRuntime( 8854): FATAL EXCEPTION: main
10-27 16:08:07.589 E/AndroidRuntime( 8854): Process: com.android.vpndialogs, PID: 8854
10-27 16:08:07.589 E/AndroidRuntime( 8854): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog}: java.lang.ClassNotFoundException: Didn't find class "com.android.vpndialogs.ConfirmDialog" on path: DexPathList[[zip file "/system/priv-app/VpnDialogs/VpnDialogs.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2284)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2435)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at android.app.ActivityThread.access$900(ActivityThread.java:153)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at android.os.Looper.loop(Looper.java:135)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at android.app.ActivityThread.main(ActivityThread.java:5375)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at java.lang.reflect.Method.invoke(Native Method)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at java.lang.reflect.Method.invoke(Method.java:372)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
10-27 16:08:07.589 E/AndroidRuntime( 8854): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.vpndialogs.ConfirmDialog" on path: DexPathList[[zip file "/system/priv-app/VpnDialogs/VpnDialogs.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2274)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	... 11 more
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	Suppressed: java.io.IOException: Entry not found
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at dalvik.system.DexFile.openDexFileNative(Native Method)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at dalvik.system.DexFile.<init>(DexFile.java:80)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at dalvik.system.DexFile.<init>(DexFile.java:59)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:270)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:239)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at dalvik.system.DexPathList.<init>(DexPathList.java:117)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:361)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:171)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:648)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at android.app.ActivityThread.handleBindApplication(<Xposed>)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at android.app.ActivityThread.access$1600(ActivityThread.java:153)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1385)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		... 8 more
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	Caused by: java.io.IOException: Failed to open file '/data/dalvik-cache/arm/system@priv-app@VpnDialogs@VpnDialogs.apk@classes.dex': Permission denied
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		... 24 more
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	Suppressed: java.lang.ClassNotFoundException: com.android.vpndialogs.ConfirmDialog
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at java.lang.Class.classForName(Native Method)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-27 16:08:07.589 E/AndroidRuntime( 8854): 		... 14 more
10-27 16:08:07.589 E/AndroidRuntime( 8854): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
10-27 16:08:07.617 W/ActivityManager(  840):   Force finishing activity 1 com.android.vpndialogs/.ConfirmDialog
10-27 16:08:07.619 W/ActivityManager(  840):   Force finishing activity 2 eu.faircode.netguard/.ActivityMain
```

Unfortunately there is nothing I can do to detect / handle this situation, since Android force finishes NetGuard (last line), which is unfairly, since NetGuard is not causing this problem.

**Comment by pylerSM** [comment]
maybe you deleted VpnDialogs.apk?

**Comment by M66B** [comment]
@pylerSM good thinking!

**Comment by pylerSM** [comment]
If so, I believe you can check for VpnDialogs package ("com.android.vpndialogs") and if it is not available and then you can show some warning and do not try to do VPN stuff.

**Comment by M66B** [comment]
I have already tried this, but it is not possible with an app class loader.
Moreover, the VpnDialog doesn't need to have the same class name on all ROMs.

**Comment by pylerSM** [comment]
I ment package name, not class name to check.

**Comment by M66B** [comment]
It is not guaranteed to be the same on all devices, but I will add it to the debug info.

**Comment by Primokorn** [comment]
I do have VpnDialogs.apk into /system/priv-app.
Version 5.1.1-1837d7aafb

**Comment by M66B** [comment]
So, it is really a bug in the ROM.

**Comment by Primokorn** [comment]
Ok, no problem. Thanks for looking at this log.
